services:
  app:
    image: node:18-alpine
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "npm start prod"
    restart: always
    ports:
      - 3443:3443
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules
  # mongodb:
  #   image: mongo
  #   container_name: mongodb
  #   restart: always
  #   ports:
  #     - 27017:27017
  #   volumes:
  #     - ./mongodb:/data/db
